accounts/urls.py
# accounts/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

ferramentas/urls.py
from django.urls import path
from ferramentas.views import termos, submit, relatorio,lista_relatorios

app_name = 'ferramentas'
urlpatterns = [
    path('relatorio/', relatorio, name='relatorio'),  # Ferramentas
    path('termos/', termos, name='termos'),  # Termos
    path('submit/', submit, name='submit'),  # Submissão do formulário
    path('relatorio/', relatorio, name='relatorio'),  # Relatório
    path('lista_relatorios/', lista_relatorios, name='lista_relatorios'),  # Lista de relatórios
    
]

src/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from ferramentas.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="home"),  
    path('ferramentas/', include("ferramentas.urls"),name="ferramentas"), 
    path('accounts/', include('accounts.urls'), name="login"), 
]

# Adicionar URLs para servir arquivos estáticos durante o desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255)
    cuca = models.CharField(max_length=255)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'full_name', 'cuca']

ferramentas/models.py
from django.db import models
from accounts.models import CustomUser
from datetime import datetime as Datetime
from datetime import datetime, time
from django.utils import timezone

def default_created_at():
    return datetime.combine(timezone.now().date(), time(8, 0))


class Formulario(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,default=1)
    nome = models.CharField(max_length=100)
    cuca = models.CharField(max_length=100)
    data_atual = models.CharField(max_length=100)
    periodo = models.CharField(max_length=100)
    atividades_realizadas = models.TextField()
    problemas_enfrentados = models.TextField()
    curiosidade_aprendizado = models.TextField()
    pontos_forts = models.TextField()
    imagem1 = models.ImageField(upload_to='images/')
    txt_img1 = models.TextField()
    imagem2 = models.ImageField(upload_to='images/')
    txt_img2 = models.TextField()
    imagem3 = models.ImageField(upload_to='images/')
    txt_img3 = models.TextField()
    imagem4 = models.ImageField(upload_to='images/')
    txt_img4 = models.TextField()
    imagem5 = models.ImageField(upload_to='images/', blank=True, null=True)
    txt_img5 = models.TextField(blank=True, null=True)
    imagem6 = models.ImageField(upload_to='images/', blank=True, null=True)
    txt_img6 = models.TextField(blank=True, null=True)
    link_relatorio = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    full_name = forms.CharField(max_length=255)
    cuca = forms.CharField(max_length=255)

    class Meta:
        model = CustomUser
        fields = ('username', 'full_name', 'cuca', 'email', 'password1', 'password2')

accounts/views.py
# accounts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import CustomUserCreationForm
from .models import CustomUser

def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Email ou senha incorretos.')
    return render(request, 'accounts/login.html')

def logout_view(request):
    logout(request)
    return redirect('login')

def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            login(request, user)
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

src/views.py
# myproject/views.py
from django.shortcuts import redirect,render

def initial_view(request):
    if request.user.is_authenticated:
        return redirect('home')
    return redirect('login')

templates/accounts/index.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Signin Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">

    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="sign-in.css" rel="stylesheet">
  </head>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2024</p>
  </form>
</main>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>

templates/accounts/login.html
<!-- accounts/templates/accounts/login.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Login</title>

</head>
<body>
    <main>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" required>
            <label for="password">Senha:</label>
            <input type="password" name="password" id="password" required>
            <button type="submit">Login</button>
        </form>
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <p>Não tem uma conta? <a href="{% url 'signup' %}">Registre-se</a></p>
    </main>
</body>
</html>

templates/accounts/signup.html
<!-- accounts/templates/accounts/signup.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Signup</title>
</head>
<body>
    <main>
        <h2>Signup</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Signup</button>
        </form>
    </main>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block extracss %} {% endblock extracss %}
    <title>{{title.title}}</title>
  </head>
  <body>
    <header class="header">
      <div class="logo">
        <h1>Juvtech</h1>
      </div>
      <div class="nav">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'ferramentas:lista_relatorios' %}">Relatórios</a>
        <a href="{% url 'home' %}">Perfil❌</a>
        {% if user.is_authenticated %}
        <p>Olá, {{ user.username }}!</p>
        <a id="red" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a> |
        <a id="blue" href="{% url 'signup' %}">Signup</a>
        {% endif %}
      </div>
    </header>
    <div class="content">{% block content %}{% endblock content %}</div>
    {% block extrajs %} {% endblock extrajs %}
  </body>
</html>

templates/form.html
{% extends "base.html" %} {% load static %} {% block extracss %} <link
rel="stylesheet" href={% static "css/form.css" %}> {% endblock extracss %}
{%block content %}

<form
  action="{% url 'ferramentas:submit' %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <h1>Formulário de relatório para o JuvTech</h1>

  <label for="nome">Nome completo:</label>
  <input
    type="text"
    id="nome"
    name="nome"
    placeholder="Ex: Maria José Pereira"
    required
  /><br /><br />

  <label for="cuca">Cuca de atuação:</label>
  <select id="cuca" name="cuca">
    <option value="PICI">PICI</option>
    <option value="JOSE WALTER">JOSE WALTER</option>
    <option value="BARRA">BARRA</option>
  </select>

  <label for="data_atual">Data do relatório:</label>
  <input
    type="text"
    id="data_atual"
    name="data_atual"
    placeholder="Ex: 22 de junho"
    required
  /><br /><br />

  <label for="periodo">Escolha o período do relatório:</label>
  <select id="periodo" name="periodo">
    <option value="MAIO - JUNHO">MAIO - JUNHO</option>
    <option value="JUNHO - JULHO">JUNHO - JULHO</option>
    <option value="JULHO - AGOSTO">JULHO - AGOSTO</option>
    <option value="AGOSTO - SETEMBRO">AGOSTO - SETEMBRO</option>
    <option value="SETEMBRO - OUTUBRO">SETEMBRO - OUTUBRO</option>
    <option value="OUTUBRO - NOVEMBRO">OUTUBRO - NOVEMBRO</option>
    <option value="NOVEMBRO - DEZEMBRO">NOVEMBRO - DEZEMBRO</option>
    <option value="DEZEMBRO - JANEIRO">DEZEMBRO - JANEIRO</option>
  </select>

  <label for="atividades_realizadas">Atividades realizadas:</label>
  <textarea
    id="atividades_realizadas"
    name="atividades_realizadas"
    placeholder="Nesse mês pude aprender mais sobre..."
    required
  ></textarea
  ><br /><br />

  <label for="problemas_enfrentados">Problemas enfrentados:</label>
  <textarea
    id="problemas_enfrentados"
    name="problemas_enfrentados"
    placeholder="Nesse enfrentei um problema em..."
    required
  ></textarea
  ><br /><br />

  <label for="curiosidade_aprendizado">Curiosidade de algum conteúdo:</label>
  <textarea
    id="curiosidade_aprendizado"
    name="curiosidade_aprendizado"
    placeholder="Queria aprender mais sobre o assunto..."
    required
  ></textarea
  ><br /><br />

  <label for="pontos_forts">Pontos a Melhorar:</label>
  <textarea
    id="pontos_forts"
    name="pontos_forts"
    placeholder="Acredito que a monitoria seria mais proveitosa se..."
    required
  ></textarea
  ><br /><br />

  <label for="imagem1">Selecione uma imagem (PNG/JPG/JPEG):</label>
  <input type="file" id="imagem1" name="imagem1" accept="image/*" /><br /><br />
  <label for="txt_img1">Texto da imagem 1:</label>
  <textarea
    id="txt_img1"
    name="txt_img1"
    placeholder="(EX: 23/04/2024 / Atividade sobre Portugol)"
    required
  ></textarea
  ><br /><br />

  <label for="imagem2">Selecione uma imagem (PNG/JPG/JPEG):</label>
  <input type="file" id="imagem2" name="imagem2" accept="image/*" /><br /><br />
  <label for="txt_img2">Texto da imagem 2:</label>
  <textarea
    id="txt_img2"
    name="txt_img2"
    placeholder="(EX: 23/04/2024 / Atividade sobre Portugol)"
    required
  ></textarea
  ><br /><br />

  <label for="imagem3">Selecione uma imagem (PNG/JPG/JPEG):</label>
  <input type="file" id="imagem3" name="imagem3" accept="image/*" /><br /><br />
  <label for="txt_img3">Texto da imagem 3:</label>
  <textarea
    id="txt_img3"
    name="txt_img3"
    placeholder="(EX: 23/04/2024 / Atividade sobre Portugol)"
    required
  ></textarea
  ><br /><br />

  <label for="imagem4">Selecione uma imagem (PNG/JPG/JPEG):</label>
  <input type="file" id="imagem4" name="imagem4" accept="image/*" /><br /><br />
  <label for="txt_img4">Texto da imagem 4:</label>
  <textarea
    id="txt_img4"
    name="txt_img4"
    placeholder="(EX: 23/04/2024 / Atividade sobre Portugol)"
    required
  ></textarea
  ><br /><br />

  <hr />
  <h2>Imagens Opcionais⬇</h2>
  <hr />
  <br />

  <label for="imagem5">Selecione uma imagem (PNG/JPG/JPEG):</label>
  <input type="file" id="imagem5" name="imagem5" accept="image/*" /><br /><br />
  <label for="txt_img5">Texto da imagem 5:</label>
  <textarea
    id="txt_img5"
    name="txt_img5"
    placeholder="(EX: 23/04/2024 / Atividade sobre Portugol)"
  ></textarea
  ><br /><br />

  <label for="imagem6">Selecione uma imagem (PNG/JPG/JPEG):</label>
  <input type="file" id="imagem6" name="imagem6" accept="image/*" /><br /><br />
  <label for="txt_img6">Texto da imagem 6:</label>
  <textarea
    id="txt_img6"
    name="txt_img6"
    placeholder="(EX: 23/04/2024 / Atividade sobre Portugol)"
  ></textarea
  ><br /><br />

  <button type="submit">Enviar</button>
</form>
{% endblock content %}

templates/index.html
{% extends "base.html" %} {% load static %} {% block extracss %}
<link rel="stylesheet" href="{% static 'css/ferramentas.css' %}" />
{% endblock extracss %} {% load static %} {% block content %}
<div class="ferramentas">
  <h1>Ferramentas</h1>
  <div class="card-ferramenta">
    <a href="{% url 'ferramentas:relatorio' %}">
      <h2>Gerador de relatório</h2>
    </a>
  </div>
</div>
<div>{% endblock content %}</div>

templates/lista_relatorios.html
{% extends "base.html" %}{% load static %}

{% block extracss %}
<link rel="stylesheet" href={% static "css/lista_relatorios.css" %}>
{% endblock extracss %}


{% block content %}
<div class="content">
{% if relatorios %}
<div class="relatorios">
    {% for relatorio in relatorios %}
    
    <div class="card-relatorio" data-report-url="{{ relatorio.link_relatorio }}">
    </div>
    <h2>{{ relatorio.nome }}</h2>
    <span>{{ relatorio.created_at }}</span>
    <h2>Se ao clicar no documento o dowload não iniciar, copie o link abaixo e cole no navegador para fazer o dowload do documento</h2>
    <a id="button_copy" href="{{ relatorio.link_relatorio }}" download>Copiar link</a>

    {% endfor %}
{% else %}
</div>
<h1>Nenhum relatório encontrado</h2>
{% endif %}

</div>
{% endblock content %}
{% block extrajs %}
<script src={% static "js/lista_relatorio.js" %}></script>
{% endblock extrajs %}

templates/report_template.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Relatório</title>
</head>
<body>
    <h1>RELATÓRIO</h1>
    <p><strong>NOME COMPLETO:</strong> {{ nome }}</p>
    <p><strong>PROJETO:</strong> PROGRAMA FUTUROS</p>
    <p><strong>PERÍODO:</strong> {{ periodo }}</p>
    <p><strong>CUCA:</strong> {{cuca}}</p>
    
    <h2>Atividades Realizadas</h2>
    <p>{{ atividades_realizadas }}</p>
    
    <h2>Desafios Enfrentados</h2>
    <p>{{ problemas_enfrentados }}</p>
    
    <h2>Curiosidade em Aprender</h2>
    <p>{{ curiosidade_aprendizado }}</p>
    
    <h2>Pontos a Melhorar</h2>
    <p>{{ pontos_forts }}</p>
    
    <p>Fortaleza, {{ data_atual }} de 2024.</p>
    <p>_____________________________________________________________</p>
    <p>{{ nome }}</p>

    <h2>Registro Fotográfico</h2>
    {% if imagem1 %}
        <img src="{{ imagem1 }}" alt="Imagem 1">
        <p>{{ txt_img1 }}</p>
    {% endif %}
    {% if imagem2 %}
        <img src="{{ imagem2 }}" alt="Imagem 2">
        <p>{{ txt_img2 }}</p>
    {% endif %}
    {% if imagem3 %}
        <img src="{{ imagem3 }}" alt="Imagem 3">
        <p>{{ txt_img3 }}</p>
    {% endif %}
    {% if imagem4 %}
        <img src="{{ imagem4 }}" alt="Imagem 4">
        <p>{{txt_img4}}</p>
    {% endif %}

    {% if imagem5 %}
        <img src="{{ imagem5 }}" alt="Imagem 5">
        <p>{{txt_img6}}</p>
    {% endif %}

    {% if imagem6 %}
        <img src="{{ imagem6 }}" alt="Imagem 6">
        <p>{{txt_img6}}</p>
    {% endif %}
</body>
</html>

templates/sucesso.html
{% extends "base.html" %}
{% block extracss %}
<link rel="stylesheet" href="{% static 'css/sucesso.css' %}">
{% endblock extracss %}
{% block content %}
<h1>Sucesso ao enviar o formulario</h1>
<p>Baixe-o no link abaixo o arquivo com os dados enviados</p>
{% url "ferramentas:lista_relatorios" %}
{% endblock content %}

templates/upload_form.html
<h1>Envie seu documento</h1>
<form
  method="post"
  action="{% url 'ferramentas:upl' %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <input type="file" name="document" required />
  <input type="submit" value="Upload" />
</form>